sudo: required
services: 
  - docker

script:
  - docker build -t luisatomo/node .
  - docker images luisatomo/node

before_deploy:
  - docker login -u luisatomo -p a123456B!

deploy:
  provider: script
  script: docker push luisatomo/node
  on:
    branch: master
    
